# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_xSen7UlpHN0olb9VqlUq7tcS1VchOKt
"""

# app.py
# Gideon Thuku's AI Caregiver's Companion

import streamlit as st
from PIL import Image
import numpy as np
import re

# --- AI Model Imports ---
# We are catching the (potential) import errors here
# This makes debugging on Streamlit Cloud easier.
try:
    import tensorflow as tf
    from tensorflow.keras.applications.mobilenet_v2 import MobileNetV2, preprocess_input, decode_predictions
    from tensorflow.keras.preprocessing import image
except ImportError:
    st.error("TensorFlow (keras) not installed. Please add 'tensorflow' to requirements.txt")

try:
    from transformers import pipeline
except ImportError:
    st.error("Transformers not installed. Please add 'transformers' to requirements.txt")

try:
    import torch
except ImportError:
    st.error("PyTorch not installed. Please add 'torch' to requirements.txt")

# -------------------------------------------------------------------
# KNOWLEDGE BASE FOR AI Q&A
# This is our "safe" database. The AI can *only* pull answers from here.
# I have added detailed sections, including AUTISM as requested.
# -------------------------------------------------------------------
CARE_KNOWLEDGE_BASE = """
    section: What is Autism Spectrum Disorder (ASD)?
    content: Autism Spectrum Disorder (ASD) is a developmental disability that can cause significant social, communication, and behavioral challenges. There is often nothing about how people with ASD look that sets them apart from other people, but they may communicate, interact, behave, and learn in ways that are different from most other people. The learning, thinking, and problem-solving abilities of people with ASD can range from gifted to severely challenged. Some people with ASD need a lot of help in their daily lives; others need less.

    section: What are common signs of Autism (ASD)?
    content: People with ASD may have difficulty with social communication and interaction, have restricted interests, and display repetitive behaviors. Signs can include:
    - Avoiding or not keeping eye contact.
    - Not responding to their name by 9 months of age.
    - Not showing facial expressions like happy, sad, angry, and surprised by 9 months of age.
    - Having trouble understanding other people’s feelings or talking about their own feelings.
    - Repeating words or phrases over and over (echolalia).
    - Getting upset by minor changes in a routine.
    - Having very specific and intense interests.
    - Showing hand-flapping, body rocking, or spinning in circles.

    section: What are some care tips for caregivers of someone with Autism (ASD)?
    content: Providing care for someone with ASD can be rewarding and challenging. Key tips include:
    1.  **Maintain a strict routine:** People with ASD often thrive on consistency. Keep mealtimes, school, and bedtime schedules the same every day.
    2.  **Use clear, simple communication:** Speak clearly and use simple, concrete sentences. Give one instruction at a time.
    3.  **Be aware of sensory sensitivities:** Many people with ASD are highly sensitive to sounds, lights, textures, or smells. Identify these triggers and try to minimize them.
    4.  **Use visual aids:** Visual supports like picture schedules, story-based interventions, and visual timers can be very effective.
    5.  **Focus on positive reinforcement:** Reward good behavior often and with enthusiasm. Be specific about what behavior you are praising.
    6.  **Ensure safety:** People with ASD may have a tendency to wander or may not be aware of dangers. Secure your home as needed.
    7.  **Find support:** You are not alone. Connect with other families, therapists, and support groups.

    section: What is Dysphagia (swallowing difficulty)?
    content: Dysphagia is the medical term for swallowing difficulties. Some people with dysphagia have problems swallowing certain foods or liquids, while others can't swallow at all. It's a common issue for people with conditions like Cerebral Palsy, stroke, or advanced dementia. Key signs include coughing or choking when eating or drinking, a gurgly-sounding voice after eating, and frequent throat clearing. Food texture modification is a primary way to manage this.

    section: What is Cerebral Palsy (CP)?
    content: Cerebral Palsy (CP) is a group of disorders that affect a person's ability to move and maintain balance and posture. CP is caused by abnormal brain development or damage to the developing brain that affects a person’s ability to control their muscles. Symptoms vary widely but can include stiff muscles (spasticity), uncontrollable movements (dyskinesia), or poor balance and coordination (ataxia).

    section: What are pressure sores?
    content: Pressure sores (also called bedsores or pressure ulcers) are injuries to the skin and underlying tissue resulting from prolonged pressure on the skin. They most often develop on skin that covers bony areas of the body, such as the heels, ankles, hips, and tailbone. People who are in a wheelchair or bed for long periods are at high risk. Caregivers must help by:
    1.  **Repositioning:** Regularly changing the person's position (e.g., every 2 hours in bed, every 15-30 minutes in a chair).
    2.  **Skin Inspection:** Checking the skin daily for red or discolored areas.
    3.  **Nutrition:** Ensuring good nutrition and hydration.
    4.  **Support Surfaces:** Using special cushions or mattresses that relieve pressure.
"""

# -------------------------------------------------------------------
# CUSTOM CSS (Royal Purple & Yellow Theme)
# -------------------------------------------------------------------
def inject_css():
    st.markdown("""
        <style>
        /* --- Main Colors --- */
        :root {
            --primary-color: #7B1FA2; /* Royal Purple */
            --accent-color: #F9A825; /* Strong Yellow */
            --bg-color: #FFFDE7; /* Soft Parchment Yellow */
            --text-color: #333333;
            --card-bg: #FFFFFF;
        }

        /* --- Global --- */
        [data-testid="stAppViewContainer"] {
            background-color: var(--bg-color);
            color: var(--text-color);
        }

        /* --- Sidebar --- */
        [data-testid="stSidebar"] {
            background-color: var(--card-bg);
            border-right: 2px solid var(--primary-color);
        }
        [data-testid="stSidebar"] h1 {
            color: var(--primary-color);
            text-align: center;
            font-size: 2.5rem;
            font-weight: 700;
        }
        /* Sidebar Radio Buttons */
        [data-testid="stRadio"] label {
            font-size: 1.1rem;
            padding: 10px 15px;
            border-radius: 10px;
            transition: 0.3s;
        }
        [data-testid="stRadio"] label:hover {
            background-color: rgba(123, 31, 162, 0.1);
        }

        /* --- Main Content --- */
        h1, h2, h3 {
            color: var(--primary-color);
            font-weight: 700;
        }
        h2 {
            border-bottom: 3px solid var(--accent-color);
            padding-bottom: 5px;
        }

        /* --- Buttons --- */
        .stButton button {
            background-color: var(--primary-color);
            color: white;
            border-radius: 10px;
            padding: 10px 20px;
            font-size: 1.1rem;
            font-weight: 600;
            border: none;
            transition: 0.3s;
        }
        .stButton button:hover {
            background-color: var(--accent-color);
            color: var(--text-color);
        }
        .stButton button:disabled {
            background-color: #cccccc;
        }

        /* --- Cards --- */
        .card {
            background: var(--card-bg);
            border-radius: 15px;
            padding: 25px;
            box-shadow: 0 4px 12px rgba(0,0,0,0.1);
            margin-bottom: 20px;
        }

        /* --- Expanders (for How-to-Use) --- */
        .stExpander {
            background: var(--card-bg);
            border: 1px solid var(--primary-color);
            border-radius: 10px;
        }
        .stExpander summary {
            font-size: 1.2rem;
            font-weight: 600;
            color: var(--primary-color);
        }

        /* --- Info/Warning Boxes --- */
        [data-testid="stAlert"] {
            border-radius: 10px;
            font-size: 1.05rem;
        }
        [data-testid="stAlert"][data-baseweb="alert-negative"] {
            background-color: #FFEBEE;
            color: #C62828;
            border: 1px solid #C62828;
        }

        </style>
    """, unsafe_allow_html=True)


# -------------------------------------------------------------------
# AI MODEL LOADING (Cached)
# -------------------------------------------------------------------

@st.cache_resource
def load_food_model():
    """Loads the pre-trained MobileNetV2 model for food analysis."""
    st.write("Cache Miss: Loading Food CV Model (first time only)...")
    model = MobileNetV2(weights='imagenet')
    return model

@st.cache_resource
def load_qa_pipeline():
    """Loads the NLP Question-Answering pipeline."""
    st.write("Cache Miss: Loading Q&A NLP Model (first time only)...")
    # This model is fast and good at extracting answers from a context
    qa_pipeline = pipeline("question-answering", model="distilbert-base-cased-distilled-squad", framework="pt")
    return qa_pipeline

# -------------------------------------------------------------------
# 1. HOME PAGE
# -------------------------------------------------------------------
def render_home_page():
    st.markdown("<div class='card'>", unsafe_allow_html=True)
    st.title("Welcome to the AI Caregiver's Companion")
    st.markdown("""
    This toolkit is designed for parents, family, and caregivers of persons with disabilities.
    Our mission is to use AI in a **safe, ethical, and supportive** way to help you find
    answers and build confidence.
    """)
    st.markdown("</div>", unsafe_allow_html=True)

    # --- CRITICAL ETHICS DISCLAIMER (WEEK 6) ---
    st.header("⚠️ Important Medical Disclaimer")
    st.warning("""
    **This is a technology project, NOT a medical device.**

    1.  The information provided by this app is for **educational and informational purposes only**.
    2.  It is **NOT a substitute** for professional medical advice, diagnosis, or treatment.
    3.  **Always** consult with a qualified healthcare provider, doctor, or therapist
        with any questions you may have regarding a medical condition or care plan.
    4.  Never disregard professional medical advice or delay in seeking it because of
        something you have read on this website.
    """)

    st.header("About The Tools")
    st.markdown("<div class='card'>", unsafe_allow_html=True)
    st.subheader("🍎 Food Texture Analyzer")
    st.markdown("""
    **What it is:** A Computer Vision (CV) tool.
    **How it helps:** Helps caregivers assess food safety. If you are caring for
    someone with **Dysphagia** (swallowing difficulties), food texture is critical.
    This tool identifies food and provides general information on its common texture.
    """)
    st.subheader("❓ Caregiver Q&A")
    st.markdown("""
    **What it is:** An NLP (Natural Language Processing) tool.
    **How it helps:** Provides safe, pre-vetted answers to common questions about
    disabilities like **Autism (ASD)**, Cerebral Palsy, and general care.
    The AI *extracts* answers from a built-in knowledge base, it does not
    "make up" its own, ensuring the information is reliable.
    """)
    st.markdown("</div>", unsafe_allow_html=True)


# -------------------------------------------------------------------
# 2. FOOD TEXTURE ANALYZER PAGE (AI-CV)
# -------------------------------------------------------------------
def render_food_analyzer_page():
    st.header("🍎 Food Texture Analyzer")

    with st.expander("📖 How to Use This Tool", expanded=False):
        st.markdown("""
        This tool helps you identify a food and understand its typical texture. This is
        especially important for individuals with **Dysphagia** (swallowing difficulties).

        1.  **Upload:** Take or upload a clear photo of a single food item.
        2.  **Analyze:** The AI will identify the food (e.g., "banana", "mashed potato").
        3.  **Review:** The tool will provide a general safety guide for that food's texture.

        **Remember:** This AI is not perfect. Always follow your therapist's specific
        instructions and **mash, cut, or puree food as advised.**
        """)

    # --- Food Texture Database (Simple) ---
    # This maps the AI's guess (from ImageNet) to our safety advice
    TEXTURE_GUIDE = {
        "banana": ("LEVEL 1: Soft", "Generally soft, but can be a choking hazard. Best to mash thoroughly."),
        "mashed_potato": ("LEVEL 1: Soft / Pureed", "Excellent. A common 'safe' texture. Ensure no lumps."),
        "broccoli": ("LEVEL 3: Hard / Chewy", "DANGER. Must be steamed very soft and mashed or pureed."),
        "carrot": ("LEVEL 4: Hard / Crunchy", "DANGER. Raw carrots are a major choking hazard. Must be cooked soft and mashed."),
        "apple": ("LEVEL 4: Hard / Crunchy", "DANGER. Raw apples are a choking hazard. Must be cooked to a soft sauce (applesauce)."),
        "orange": ("LEVEL 2: Soft / Stringy", "CAUTION. Soft, but membranes can be stringy. Best to use juice or fully pureed."),
        "bread": ("LEVEL 3: Chewy / Pasty", "CAUTION. Can be very difficult. It can clump and become pasty in the mouth."),
        "ice_cream": ("LEVEL 1: Pureed / Liquid", "Good, but melts to a 'thin liquid', which can be hard for some to control."),
        "default": ("Unknown Texture", "Could not identify. Please consult a professional. Do not assume it is safe.")
    }

    uploaded_file = st.file_uploader("Upload a photo of a food item", type=["jpg", "jpeg", "png"])

    if uploaded_file is not None:
        st.image(uploaded_file, caption="Uploaded Food", use_column_width=True)

        if st.button("Analyze Food Texture"):
            with st.spinner("AI is analyzing the image..."):
                try:
                    model = load_food_model()

                    # Process the image for the model
                    img = Image.open(uploaded_file).convert('RGB')
                    img = img.resize((224, 224))
                    img_array = image.img_to_array(img)
                    img_array = np.expand_dims(img_array, axis=0)
                    img_array = preprocess_input(img_array)

                    # Get predictions
                    preds = model.predict(img_array)
                    decoded_preds = decode_predictions(preds, top=3)[0]

                    st.subheader("AI Analysis Results:")

                    # --- Logic to find the food and map it ---
                    found_food = False
                    for _, label, prob in decoded_preds:
                        if label in TEXTURE_GUIDE:
                            level, advice = TEXTURE_GUIDE[label]
                            st.markdown(f"**Identified:** {label.replace('_', ' ').title()} ({(prob * 100):.1f}% confidence)")
                            st.info(f"**Texture Guide:** {level}")
                            st.markdown(f"**Caregiver Advice:** {advice}")
                            found_food = True
                            break # Stop on the first match

                    if not found_food:
                        # If no known food is found, show the default
                        level, advice = TEXTURE_GUIDE["default"]
                        st.error(f"**Identified:** {decoded_preds[0][1].replace('_', ' ').title()}")
                        st.warning(f"**Texture Guide:** {level}")
                        st.markdown(f"**Caregiver Advice:** {advice}")

                except Exception as e:
                    st.error(f"An error occurred during analysis: {e}")


# -------------------------------------------------------------------
# 3. CAREGIVER Q&A PAGE (AI-NLP)
# -------------------------------------------------------------------
def render_qa_page():
    st.header("❓ Caregiver Q&A")

    with st.expander("📖 How to Use This Tool", expanded=False):
        st.markdown("""
        This tool uses AI to answer your questions about disabilities and caregiving.

        1.  **Ask a Question:** Type a specific question in the text box. Try to be clear.
        2.  **Get an Answer:** The AI will read its **built-in, safe knowledge base**
            and find the most relevant section to answer your question.

        **This is an *extraction* AI, not a *generative* one.** It cannot "think" or
        give custom advice. It only finds and shows you pre-written, safe information.

        **Good Questions:**
        * "What are common signs of autism?"
        * "How do I prevent pressure sores?"
        * "What is dysphagia?"
        """)

    st.markdown("<div class='card'>", unsafe_allow_html=True)
    question = st.text_input("Ask a question about caregiving or a specific disability:",
                             placeholder="e.g., What are some care tips for autism?")

    if st.button("Get AI-Powered Answer"):
        if not question.strip():
            st.warning("Please ask a question.")
        else:
            with st.spinner("AI is searching the knowledge base..."):
                try:
                    qa_pipeline = load_qa_pipeline()

                    # This is the core AI task:
                    # It finds the answer to the 'question' within the 'CARE_KNOWLEDGE_BASE'
                    result = qa_pipeline(question=question, context=CARE_KNOWLEDGE_BASE)

                    st.subheader("Answer Found by AI:")

                    # Check if the AI is confident
                    if result['score'] < 0.1: # Confidence threshold
                        st.warning("I couldn't find a specific answer for that in my knowledge base. Try rephrasing your question.")
                    else:
                        st.success(result['answer'])

                        # For transparency, show *where* the AI got the answer
                        st.markdown("---")
                        st.markdown(f"**Source (from Knowledge Base):**")

                        # Find the full "section" the answer came from
                        # This makes the answer more useful
                        for section in CARE_KNOWLEDGE_BASE.split("section:")[1:]:
                            if result['answer'] in section:
                                st.markdown(f"...{section.replace('content:', '')}...")
                                break

                except Exception as e:
                    st.error(f"An error occurred while running the AI model: {e}")

    st.markdown("</div>", unsafe_allow_html=True)


# -------------------------------------------------------------------
# MAIN APP LOGIC & NAVIGATION
# -------------------------------------------------------------------
def main():
    # Load the custom CSS
    inject_css()

    # --- Sidebar ---
    st.sidebar.markdown("<h1>♿</h1>", unsafe_allow_html=True)
    st.sidebar.title("Caregiver's Companion")

    # Navigation Radio Buttons
    page_options = {
        "🏠 Home": render_home_page,
        "🍎 Food Analyzer (AI-CV)": render_food_analyzer_page,
        "❓ Caregiver Q&A (AI-NLP)": render_qa_page
    }

    selected_page = st.sidebar.radio("Choose a Tool:", page_options.keys())

    st.sidebar.markdown("---")
    st.sidebar.info("Built by Gideon Thuku for the 'AI for Software Engineering' course.")

    # --- Render the selected page ---
    page_options[selected_page]()

if __name__ == "__main__":
    main()